version: '3.7'
services:
  jaeger:
    network_mode: host
    image: jaegertracing/all-in-one:latest
    environment:
      - SPAN_STORAGE_TYPE=grpc-plugin
      - GRPC_STORAGE_PLUGIN_BINARY=/usr/bin/jaeger-redisearch-linux-amd64
      - GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE=/etc/jaeger-redisearch/config.yaml
    depends_on:
      - redis
    volumes:
      - ./bin/jaeger-redisearch-linux-amd64:/usr/bin/jaeger-redisearch-linux-amd64
      - ./configs/config.yaml:/etc/jaeger-redisearch/config.yaml
    ports:
      - "6831:6831/udp"
      - "14269:14269"
      - "16686:16686"
      - "9090:9090"
  hotrod:
    network_mode: host
    image: jaegertracing/example-hotrod:latest
    ports: 
      - "8081:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=localhost
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
  
  tracegen:
    network_mode: host
    image: jaegertracing/jaeger-tracegen:latest
    environment:
      - JAEGER_AGENT_HOST=localhost
      - JAEGER_AGENT_PORT=6831
    command: ["-duration", "60s", "-workers", "10", "-pause", "250ms"]
    depends_on:
      - jaeger

  redis:
    image: redislabs/redisearch:latest
    ports: 
      - "6379:6379"
