name: Release

on:
  push:
    tags: ['[0-9]+\.[0-9]+\.[0-9]+']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Create release distribution
        run: make build-all-platforms tar-all-platforms

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
         registry: ${{ env.REGISTRY }}
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        if: github.event_name != 'pull_request'
        run: |
          export DOCKER_TAG=${GITHUB_REF##*/}
          make docker-build docker-push

      - name: Create Github release
        run: |
          export TAG=${GITHUB_REF##*/}
          gh release create ${TAG} --title "Release ${TAG}" *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}